- platform: broadlink
  host: 192.168.2.102
  mac: '34:ea:34:51:25:54'
  timeout: 15
  switches:
    # Main light
    main_light_up:
      friendly_name: "Light Brightness"
      command_on:  'JgBQAAABKZMUERQ2FBEUERQRFREUERQ2FDYUERQ2FTYUERQ2FDYUERQRFTYUERQ2FDYUNhQRFTYUNhQRFDYUERQSFBEUNhQRFAAFTgABKUgUAA0FAAAAAAAAAAA=' # up
      command_off: 'JgBQAAABJpUSExI4EhMTExITEhMSExI4EjgTExI4EjgSExI4EjgTExI4FDYUERQ2FDYUNxQRFDYUERQRFTUUEhQRFRAVNRUQFQAFTQABKEkVAA0FAAAAAAAAAAA=' # down
    main_light:
      friendly_name: "Light"
      command_on:  'JgBQAAABKJMVEBU2FBEUERQRFBEVEBU2FDYUERQ2FTUVEBU2FDYUERQRFTUVNhQRFBEUNhQRFTUVNhQRFBEUNhQ2FRAVNhQRFAAFTgABKUgVAA0FAAAAAAAAAAA=' # on
      command_off: 'JgBQAAABKZIVEBU2FBEUERQRFBEUERU1FTYUERQ2FDYUERU2FDYUERQRFDYUNhU2FDYUNhQRFDYUNhURFBEUERQRFBEUNhUQFQAFTQABKUkUAA0FAAAAAAAAAAA=' # off
    main_light_sleep:
      friendly_name: "Light Sleep"
      command_on:  'JgBQAAABKZIUERQ2FRAVERQRFBEUERQ2FTUVERQ2FDYUERQ2FTUVERQRFBEUNhQ2FTUVNhQRFDYUNhU1FREUERQRFBEUNhQRFQAFTQABKUkUAA0FAAAAAAAAAAA=' # sleep
      command_off: 'JgBQAAABKJMVEBU2FBEUERQRFBEVEBU2FDYUERQ2FTUVEBU2FDYUERQRFTUVNhQRFBEUNhQRFTUVNhQRFBEUNhQ2FRAVNhQRFAAFTgABKUgVAA0FAAAAAAAAAAA=' # on
    # Amply 
    amply:
      friendly_name: "Amply"
      command_on:  'JgBYAAABJpQSExE5ERMSExE5EhMROBI4EjgSOBI4EhMSEhITERQRFBI4EjcSExE5EhMSEhM3EjgRFBEUETkSEhE5ETkSExETEgAFQgABJ0oSAAxQAAEmShMADQU=' # 
      command_off: 'JgBQAAABJZQTEhE5EhMSExE4EhMSOBE5EjgRORI4EhISExEUERMSExI4EjgRFBE5ERMSExE5ETkRExITEjgSExI4EjgSEhITEQAFQwABJ0oSAA0FAAAAAAAAAAA=' # 
    amply_input_mode:
      friendly_name: "Amply Input Mode"
      command_on:  'JgBQAAABJ5MSExI4EhMRExI4EhMSOBE5EjgSOBI3EhMRFBEUERMSExITEjgSNxI4EjgSExEUERMTNxITEhMSEhITETkRORI4EQAFQwABJkkTAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABJpQSExI4EhMSEhE5ERQSOBI4ETkSOBI3EhMSExEUERMSExE5ETkSOBI4EjcTEhITEhMRExITEhMRExITETkSOBI4EgAFQgABJkoSAA0FAAAAAAAAAAA='
    amply_volume:
      friendly_name: "Amply Volume"
      command_on:  'JgCQAAABJ5MSExE5EhISExE5EhMROBM3EhMSOBE5EhMRExITERQSEhITETkSExETEhMSExETEhMSOBITEjgSOBI4EjcSOBI4EQAFaAABJ5MTEhI4EhMRExI4EhMSOBI4ERQROBM3EhMSExETExIRFBEUEjcSExEUERQRExEUERQSOBETEjgSOBI4EjgSOBI4EgANBQAAAAAAAAAA'
      command_off: 'JgCQAAABJ5MSExI4EhMSEhE5EhMSOBE5EhISOBI4ERQRFBISERQRFBE5ETgTEhEUEhMSEhEUEhMSEhITETkSOBE5EjgRORE4EgAFaAABJZUSEhI4EhMRFBI4EhIRORE5ERQRORI4EhISExEUERMSExE5EjgSExETEhMRFBETEhMRFBETEjgSOBI4EjgSOBE5EQANBQAAAAAAAAAA'
    # Air conditioner
    aircon_off:
      friendly_name: "Aircon off"
      command_on: 'JgDWAH0/DxAOMBAPDzAPEBAvDxAPMA8QDjAQEQ0wEC8PEA8wDxAPLxAvDzAOMBAPDxEOMBAvDxAPEQ4QDxEOMBEPDhEPEA8QDxINEg4wDhEPEQ4QDxEOMQ4QDxEOEQ8QDzAPEA8QDzEOEA8QDxEOMQ4wDxAPEA8RDhEPEQ4QDxEOEQ8QDxEOEg4RDjAOMQ4RDxENEg4RDhAPEQ4SDhEOEQ4wEA8QLw8QDxAPEQ8RDhAPEQ4SDhAPEA8RDjEOEA8RDjAQLw8vEC8PEA8QDxEPLxAQDhEPLxAADQUAAA=='
    aircon_cool:
      friendly_name: "Aircon Cool"
      command_on: 'JgDWAH1ADREPMA4REC4PEQ4wDxEPMA8QDjENEg4wDzAOEQ4xDxAOMBAvDy8QLw8RDhAQMA4vEBAOEQ8RDhEOMBAQDxAOEg0xDy8QEA4RDxAPEA8RDhIOLxAQDxEOEA8wDxEOEQ4RDxAPMA4RDhEPMA8vDzAPEBAQDhEPEA4REA8PEQ4SDhAPMQ0SDhAPMA8QDxEOEQ8RDhAPEQ4RDxEPEA4wEA8QLw8RDxENEQ4RDxAPEQ8QDxEOEQ4RDjAQEA4SDTEPLw8vEDAOEBARDREPMA4wEBAOEQ4ADQUAAA=='
    aircon_dry:
      friendly_name: "Aircon Dry"
      command_on: 'JgDWAH4/Dw8PMA8QDzAPEA8wDxAPLxAQDjAQEA4wEC8PEA8vEBAOMBAvDzAOMBAPDxEOMBAvDxAPEQ4QDxEOMBAQDhEPEA8QDxIOEQ4RDhEPEA8QDxAPMBEODxEOEg4wDjAPEA8QDzEOMA8QDxEOEQ4wEA8PEQ4RDxASDg4RDhEPEA8RDhEPEQ8QDhIOLxAQDhIOEA8QDxEOEg4RDhAPEQ4wEBAOMBAQDhIOEA8QDxEOEQ8QDxEPEA4RDzAOEQ8QDzEOMA4wES0QEA4SDhEOMA8vEC8QEA8ADQUAAA=='
    aircon_heat:
      friendly_name: "Aircon Heat"
      command_on: 'JgDWAH0/DhEPLw8QDzAPEBAvDhEPMA4RDy8PEg4vEC8PEA8wDhEPLxAvEC8PLxAQDxENMBAvDxAPEg4QDxAPMA8RDREPEQ4wDy8QEA4RDxEPEA8QDxEPLw4REA8PEBAvDxAPEQ4RDy8PEQ8QDxEPEA4wEA8QEA8QDxAPEg0RDxAPEA8RDhEPMA8vEC8OMQ4QEBENEg4QDxEPEQ4RDhAPEQ8vDxAPMA8QDxEQDw8QEBAOEQ4SDxAPEA4RDy8QEA4SDi8QLxAvDy8QDw8RDhEQLw4wDxAQEA4ADQUAAA=='
    aircon_temp_18:
      friendly_name: "Aircon Temp 18"
      command_on: 'JgDWAH1ADw8PMA8QDzAPEA8wDhEPLw8RDjAQEA4wDzAOEQ8wDxAOMA8wDzAPLw8QEBEOLw8wDxAPEQ4RDxAPLw8RDhEPEA8wDxAPEQ8QDhEPEQ4RDxAPMA4RDhEPEA8wDy8QEQ0RDzAOEg0RDxAQLw8vDxEOEQ8QDxEOEQ8QDxEOEg0RDxEOEg0RDzAOMA8QDxEOEQ8QDxEOEQ8QDxAQEQ0wDxEOMA8QDxEPMA4QDxEOEQ8QDxEOEQ8QDzAPEQ4RDjEOLw8wDzAPEA8QDxAPMQ8PEDAOEQ4ADQUAAA=='
    aircon_temp_19:
      friendly_name: "Aircon Temp 19"
      command_on: 'JgDWAH4/Dw8PMA8QEC8OEQ8vDxEOMA8RDjAPEQ4wDzAOEQ8vDxEOMA8wDzAPLw8QDxEOMBAvDhEPEQ4QEBAPLw8RDhEPEA8QDzEOEQ4QDxEOEg4QDxEOMQ4QDxEPEA8wDy8PEA8RDy8PEQ4RDxEPMA4vDxEOEg4RDhEPEQ0SDw8PEQ4RDxEOEA8RDy8QMA4QEA8PEQ4RDxAPEQ8QDhEPEA8wDxAPMA4REBAOMQ4QDxEOEQ4RDxEOEQ4RDy8PEg4RDjAPLw8wDjAQEA4RDxAPEA8xDjAPEQ4ADQUAAA=='
    aircon_temp_20:
      friendly_name: "Aircon Temp 20"
      command_on: 'JgDWAHxADxAPLw8RDjAQEA4wDxAPMA8QDzAOEg4wDjAPEA8wDxAPMA8vDzEOLw8RDhIPLw8vDxAPEg0RDxAPMA4RDxAPEQ4wEC8OEQ8QDxEOEg4QDxEPMA4QEBAOEQ4wDzAPEA8QDzAPEA8RDhEOMA8wDxAPEA8SDREPEA8RDhEPEA8RDhEPEA8QDzEOLxAPDxIOEQ8QDhEPEQ4RDhEOEQ8vEBAPLw8RDhEPLxAQDhIOEQ4RDhEPEQ8QDjAQEA8QDy8PMA4wDzEOEA8QDxEOMBAvDzAPEQ4ADQUAAA=='
    aircon_temp_21:
      friendly_name: "Aircon Temp 21"
      command_on: 'JgDWAH8/DhAPMA4RDy8PEQ8vDxEOMA8QEC8PEQ4wDy8PEQ4wDxEOMBAvDzAPLw8QEBAOMBAvDhEPEQ4QEBAPLxAPDxEOEQ8QDxEOMQ4QDxEPEQ4QDxEOMQ8PDxEOEQ8vDzAQDxAQDjAQDw8RDhIOMA8vDxEPEQ0SDhEOEQ8RDhAPEA8RDhIOEA8RDjAPMA8QDxAQDw8RDhEPEA8RDhEOEQ8wDhEPLw8RDhEPMA8QDxAPEA8RDhIOEA8RDjAQEA4SDTEPLw8vDzEOEBAQDhEOEg4RDhEOEQ8ADQUAAA=='
    aircon_temp_22:
      friendly_name: "Aircon Temp 22"
      command_on: 'JgDWAHxADhEOMA8RDy8PEQ8vDxAPMA8QDzAOEg8uDzAPEA8wDxAQLw8vDzEOLxAQDhIOLxAvEA8PEQ4RDxAPMA4RDxAPEQ4wDxAPMQ4QDxAQEA4SDhEPLw8RDhEPEA4wDzEOEA8RDzAOEBAQDhEOMBAvDxAQDw8SDREPEA8RDhEPEA8RDhEOEg8PDzAOMA8RDxAPEBAQDhEOEQ8QDxEOEg4vEBAOMBAQDhIOLw8RDhEPEBAQDhEOEQ8QDzEOEQ8PDzAPMA8vDzAOEg8QDhAQLw8RDhINEg4ADQUAAA=='
    aircon_temp_23:
      friendly_name: "Aircon Temp 23"
      command_on: 'JgDWAHxADhAPMA8QDzAPEBAvDhEPMA8QDy8PEg4vDzAPEA8wDxAPMA8vEDAOLxAQDxEOLw8wDxAQEA4RDhEPMA4RDxAPEA8RDjEPMA4QEA8PEQ4SDhEOMA8RDhEOEQ4wDzEOEA8RDzAOEA8SDREPLw8wEA8PEQ4SDhAPEBAQDhEPEA8RDhEPEQ4QDzAQLw4RDxAPEA8SDREPEA8RDhIOEQ8vDhEPMA8RDhEOMA4RDxAPEQ4SDhAPEA8RDzAPEA4RDy8QMA8vDjAQEA4SDREPEA8wDxEOEQ4ADQUAAA=='
    aircon_temp_24:
      friendly_name: "Aircon Temp 24"
      command_on: 'JgDWAH1ADw8PMA8QEC8PEBAuEBAOMBAQDy8PEQ4wDzAOEQ8vEBAOMBAvDzAPLw8QEBAPLw8wDxAQEA4QEBAOMA8RDxAPEA8wDjAPMA8QEA8PEQ4SDw8QMA4RDhAQEQ0xDjAPEBAQDjAPEA8QDxEOMBAvDxAPEA8RDxAPEA8RDhIOEQ8QDxAOEQ8QDzAPLw8RDhEPEA8RDxAOEQ8QDxEOEQ8wDhEPLw8SDhAPMA4RDxAPEQ4RDhEPEA8RDjAPEQ4SDTAPMA8wDzAPEA8PDxIOMA4wDxEOEQ4ADQUAAA=='
    aircon_temp_25:
      friendly_name: "Aircon Temp 25"
      command_on: 'JgDWAH5ADhAPMA4RDy8QEA4wDxEOMBAPDzAPEQ4wDy8QEA4wEA8PMBAvDzAPLw8QEBAOMA8vEBAOEg4QDxEOMA8QDxEOEQ8QDxEOEg0xDxAOEg4QEBAOMQ8PDxEOEQ8vDzAPEQ4RDjAQEA4RDhEPMA4wEA8PEQ4RDxEOEA8RDhIPEA4RDhIOEQ4QEC8PLw8RDhEPEBAQDxEOEA8RDhEOEg4wDhIOMA8QDhEPMA8QDxAQDxAQDhIOEA8RDjAPEQ4SDTEOMA8vDzEOEA8QEBAOEg4RDy8PLw8ADQUAAA=='
    aircon_temp_26:
      friendly_name: "Aircon Temp 26"
      command_on: 'JgDWAH0/DxAOMA8QDzAPEA8wDxAPMA4RDy8QEQ4vDzAPEA8wDhEPMA4wDzEOLxAQDxEOLw8wDxAPEQ4RDhEQLw4RDxAPEA8wEA8PEQ8vEBAPEA4RDxEOMQ4QDxAPEQ4wEC8OEQ8QDzAPEA8QEBAOMA8wDxAPEBAQDhEOEQ8QDxEOEQ8RDhAPEQ4RDzAPLw8QDxINEg4QEA8PEg4RDhAPEQ8vDxAQLw8QDxEOMBAPDxIOEQ4RDhAQEQ4RDjAPEQ4RDjEOLw8xDjAOEQ8QDxAQMA4QDzAOMQ4ADQUAAA=='
    aircon_temp_27:
      friendly_name: "Aircon Temp 27"
      command_on: 'JgDWAH1ADxAPLxAQDjAPEQ4wEA8PMA8QDzAOEg8vDjAPEA8wEA8PMA8vDzEPLw4RDxEPLw4wDxEOEg4QDxAQLw8QDxEOEQ8QEC8PEQ4vDxINEg4QDxEOMQ4QDxEPEA8wDjAQDxAQDjAQDw8RDxAQLw4wDxEPEA8RDhAPEQ4REA8QEA4SDhAPEBAPDzEPLw8QDxEOEg0RDxAQEA4SDhAPEA8wDxAPMA8QDxAPMA8QDxEPEQ4RDhAPEg0SDi8QEQ0SDjAOMA8wDzAOEQ4RDxAPEBAvEC8PMA4ADQUAAA=='
    aircon_temp_28:
      friendly_name: "Aircon Temp 28"
      command_on: 'JgDWAH4/DxAPLw8RDjAPEQ8vEA8PMA8QEC8PEQ4xDTEPEA8wDxAPLw8wDjAQLw8RDhAPMQ4vEBAOEQ8QDxEOMA8RDhEPEQ4wDy8PEQ4wEA8PEQ4RDxAPMA8QEA8PEQ4wDzAPEQ4QDzAPEQ4RDhEPMA8vDxAPEQ4SDRIOEA8RDhEPEQ4QDxINEQ8RDjAPMA8QDhEPEA8RDxAPEA8RDxAOERAvDxEOMA8RDRIPLw8QDxAPEQ4SDREPEBAQDjAPEA8RDjEOMA8vDzAPEA8RDhEPLw8wDzAOMBAADQUAAA=='
    aircon_temp_29:
      friendly_name: "Aircon Temp 29"
      command_on: 'JgDWAH0/DhEPLw8RDy8QEA4wEA8PMBAPDzAPEQ8vDjAQEA4wEA8PMA8wDzAOMA4RDxEOMA8vDxEOEg4QDxAPMBAPEBAOEQ8QDxEOMQ4wDxEOEQ4QDxINMQ4RDxAPEBAvDjAPEBAQDjAPEQ4RDxAPMA4wDxEPEA8RDhAPEQ4RDxAPEQ4SDhAPEA8RDjEPLw8QDxEOEg0REA8PEQ4SDhAPEA8wEA8QLw8QDxAPMBAPDxEOEg4RDhAPEg0SDjAPEQ4RDjAPLw8wDzAPEA4RDxAPEA8RDhEPMA8ADQUAAA=='
    aircon_temp_30:
      friendly_name: "Aircon Temp 30"
      command_on: 'JgDWAH4/DhAPMA4RDzAOEQ8vDxEOMA8RDjAPEQ4wDzAOEQ8vEAwSMA8wDjEOMA8QEBAOMA8wDxAPEQ4QDxEOMA8QDxEPEBAvDhEPMA4wDxAPEQ8RDREPMA8RDhAPEQ4xDjAPEA8RDjAPEA8QDxEOMA8wDxAPEBAPDxEPEA8RDhEOEg4RDhAPEQ4RDy8PMA8QDxEPEA8QDxAPEQ4RDxAPEA8xDhAPMA8RDw8PMA8QDxEOEg4QDxAPEQ4RDzAOEg4RDjAOMA8xDjAPEA8QEBAPMA4QEBAOMQ4ADQUAAA=='
    aircon_temp_31:
      friendly_name: "Aircon Temp 31"
      command_on: 'JgDWAH5ADhAPMA4RDzAOEQ8vEBAOMA8RDjAQEA4wDy8PEQ4wEBAPLxAvDzAOMA8QDxEPLw8wDhEOEg4QDxEOMA8QDxEPEA8QDzEOMA8vDxAPEQ8RDhAPMQ4RDhAPEQ4xDy8PEA8RDjAPEA8QEBAOMBAvDhEPEA8QDxEOEQ8RDxAPEQ4RDhAPEQ4REC8PLxAPDxEOEQ8QDxEPEA8QDxAQEA4xDw8PMBAQDxAOMBAPEBAOEg4QDxEOEQ8QDzAPEQ4RDjAPLw8xDjAPEQ0RDxEPEA4wEBAOMQ8ADQUAAA=='
    aircon_temp_32:
      friendly_name: "Aircon Temp 32"
      command_on: 'JgDWAH4/Dw8QLw8QDzAOERAvDhEPLw8RDy8PEQ4wDzAOEQ8vDxEPLw8wDzAPLw8QDxEPLw8wDhEQEA4RDxAPLw8RDhEPEBAvDy8PMA8wDhEPEQ4QDxINMA8RDhEPEA8wDzAPEA4RDjAPEg0SDhEPMA4vEBAOEQ8RDhEPEA4RDxEOEQ4RDxEOEBARDTAPMQ4QDxAQEQ4RDhAPEQ8QDxAPEA8wEBAOMQ4QEBAOMQ4QEBENEg4RDhEOEQ4RDzAOEQ8QDzENMQ8vDy8QEQ0RDxAQLw8vDxEOMA8ADQUAAA=='
