# Turn on light when 8:05
- alias: 'Turn on main light at 8:00'
  trigger:
    platform: time
    at: '8:00:00'
  condition: 
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    - service: switch.turn_on
      entity_id: switch.main_light